version: '3.8'

services:
    auth-service:
        build: ../backend/auth-service
        ports:
            - "8000:8000"
        environment:
            - DATABASE_URL=postgresql://user:password@db/auth_db
        depends_on:
            - db

    db:
        image: postgres:14
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: auth_db
        ports:
            - "5432:5432"
