services:
    auth-service:
        build: ../../backend/auth-service
        container_name: auth_service
        ports:
            - "5000:5000"
        depends_on:
            - db

    db:
        image: postgres:14
        container_name: db_service
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=secret123
            - POSTGRES_DB=auth_db
        ports:
            - "5432:5432"
