%YAML 1.1
---
suricata:
  runmode: single
  logging:
    default-log-level: info
    outputs:
      - console:
          enabled: yes
      - file:
          enabled: yes
          filename: /var/log/suricata/suricata.log

af-packet:
  - interface: enp0s3
    threads: 4
    cluster-id: 99
    cluster-type: cluster_flow
    copy-mode: ips

outputs:
  - eve-log:
      enabled: yes
      filetype: regular
      filename: /var/log/suricata/eve.json
      types:
        - alert:
            payload: yes
            payload-printable: yes
            packet: yes
            http: yes
